import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { AlertCircle, ArrowUpRight, Boxes, CheckCircle2, Clock3, DollarSign, ExternalLink, Globe2, PackageCheck, RefreshCw, ShoppingCart, Sparkles, TrendingUp, Workflow, Zap } from "lucide-react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const money = (value: number) => `R$ ${(value / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`;
const channelLabel = (value: string) => value === "mercadolivre" ? "Mercado Livre" : value === "shopee" ? "Shopee" : value;

export default function Dashboard() {
  const [, navigate] = useLocation();
  const { data: connections = [], isLoading: loadingConnections } = trpc.marketplace.getConnections.useQuery();
  const { data: products = [], isLoading: loadingProducts } = trpc.products.list.useQuery();
  const { data: orders = [], isLoading: loadingOrders } = trpc.orders.list.useQuery({ limit: 10 });
  const importOrdersMutation = trpc.orders.importFromAllMarketplaces.useMutation();
  const connected = connections.filter((connection) => Boolean(connection.isConnected));
  const lowStock = products.filter((product) => Number(product.stock || 0) <= Number(product.minStock || 0));
  const pendingOrders = orders.filter((order) => !["delivered", "cancelled", "canceled"].includes(order.status || ""));
  const isLoading = loadingConnections || loadingProducts || loadingOrders;

  const syncOrders = async () => {
    try { const result = await importOrdersMutation.mutateAsync({}); toast.success(`${result.totalImported} pedido(s) atualizado(s)`); if (result.totalFailed) toast.error(`${result.totalFailed} pedido(s) falharam`); }
    catch { toast.error("Não foi possível sincronizar os pedidos agora"); }
  };

  return <div className="mx-auto max-w-[1500px] space-y-7">
    <section className="relative overflow-hidden rounded-[28px] bg-slate-950 px-6 py-7 text-white shadow-xl shadow-slate-950/10 md:px-9 md:py-8">
      <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-blue-500/20 blur-3xl" /><div className="absolute bottom-[-100px] right-[22%] h-56 w-56 rounded-full bg-violet-500/15 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.2em] text-blue-300"><Sparkles className="h-3.5 w-3.5" /> Luary Command Center</div><h1 className="max-w-2xl text-3xl font-semibold tracking-[-0.04em] md:text-4xl">Sua operação, em uma única visão.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Acompanhe canais, catálogo, estoque e pedidos em tempo real. Decida rápido com uma operação que mostra o que merece atenção.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => navigate("/produtos")} className="rounded-xl bg-white text-slate-950 hover:bg-slate-100"><Boxes className="mr-2 h-4 w-4" /> Abrir catálogo</Button><Button onClick={() => navigate("/omnichannel")} variant="outline" className="rounded-xl border-white/20 bg-white/10 text-white hover:bg-white/15 hover:text-white"><Workflow className="mr-2 h-4 w-4" /> Ver canais</Button></div></div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Canais conectados" value={isLoading ? "—" : `${connected.length}/${connections.length || 0}`} detail="Integrações ativas" icon={Globe2} tone="blue" onClick={() => navigate("/marketplaces")} />
      <MetricCard label="Produtos no catálogo" value={isLoading ? "—" : products.length.toLocaleString("pt-BR")} detail="Catálogo mestre" icon={Boxes} tone="violet" onClick={() => navigate("/produtos")} />
      <MetricCard label="Pedidos em andamento" value={isLoading ? "—" : pendingOrders.length.toLocaleString("pt-BR")} detail="Últimos pedidos importados" icon={ShoppingCart} tone="amber" onClick={() => navigate("/pedidos")} />
      <MetricCard label="Itens em atenção" value={isLoading ? "—" : lowStock.length.toLocaleString("pt-BR")} detail="Estoque abaixo do mínimo" icon={PackageCheck} tone={lowStock.length ? "rose" : "emerald"} onClick={() => navigate("/produtos")} />
    </section>

    <div className="grid gap-5 xl:grid-cols-[1.3fr_0.7fr]">
      <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Saúde da operação</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Pulso dos seus canais</h2></div><Button variant="outline" size="sm" className="w-fit rounded-xl" onClick={syncOrders} disabled={importOrdersMutation.isPending}><RefreshCw className={`mr-2 h-3.5 w-3.5 ${importOrdersMutation.isPending ? "animate-spin" : ""}`} />Sincronizar pedidos</Button></div><div className="space-y-2">{connections.length ? connections.map((connection) => <div key={connection.id} className="flex items-center justify-between rounded-2xl border border-slate-100 bg-slate-50/60 p-4 transition hover:border-slate-200 hover:bg-slate-50"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-xl ${connection.marketplaceType === "mercadolivre" ? "bg-yellow-100 text-yellow-700" : "bg-orange-100 text-orange-700"}`}><Globe2 className="h-4 w-4" /></div><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-900">{channelLabel(connection.marketplaceType)}</p><p className="truncate text-xs text-slate-400">{connection.sellerName || "Conta sem nome"}</p></div></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-[11px] text-slate-400">Última atividade</p><p className="text-xs font-medium text-slate-600">{connection.lastSyncAt ? new Date(connection.lastSyncAt as any).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Ainda não sincronizado"}</p></div><StatusPill connected={Boolean(connection.isConnected)} error={connection.lastErrorMessage} /></div></div>) : <EmptyState icon={Globe2} title="Nenhum canal conectado" description="Conecte seu primeiro marketplace para começar a centralizar a operação." action="Conectar canal" onClick={() => navigate("/marketplaces")} />}</div></section>

      <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Ações recomendadas</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Próximos movimentos</h2></div><Zap className="h-5 w-5 text-blue-500" /></div><div className="space-y-3"><ActionRow icon={lowStock.length ? AlertCircle : CheckCircle2} tone={lowStock.length ? "rose" : "emerald"} title={lowStock.length ? `${lowStock.length} item(ns) abaixo do mínimo` : "Estoque sob controle"} detail={lowStock.length ? "Revise os níveis antes de perder vendas." : "Nenhum alerta crítico neste momento."} onClick={() => navigate("/produtos")} /><ActionRow icon={pendingOrders.length ? Clock3 : CheckCircle2} tone={pendingOrders.length ? "amber" : "emerald"} title={pendingOrders.length ? `${pendingOrders.length} pedido(s) em andamento` : "Pedidos em dia"} detail={pendingOrders.length ? "Acesse a fila para acompanhar o despacho." : "Sua operação não tem pendências."} onClick={() => navigate("/pedidos")} /><ActionRow icon={Sparkles} tone="violet" title="Otimize seu catálogo" detail="Melhore score, títulos e dados estruturados." onClick={() => navigate("/seo-avancado")} /></div><Button variant="ghost" className="mt-4 w-full justify-between rounded-xl text-slate-500 hover:text-slate-950" onClick={() => navigate("/operacoes")}>Abrir central de operações <ArrowUpRight className="h-4 w-4" /></Button></section>
    </div>

    <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Feed comercial</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Pedidos recentes</h2></div><Button variant="ghost" size="sm" className="rounded-xl text-slate-500" onClick={() => navigate("/pedidos")}>Ver todos <ExternalLink className="ml-2 h-3.5 w-3.5" /></Button></div>{orders.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-[0.14em] text-slate-400"><th className="pb-3 font-semibold">Pedido</th><th className="pb-3 font-semibold">Canal</th><th className="pb-3 font-semibold">Cliente</th><th className="pb-3 text-right font-semibold">Valor</th><th className="pb-3 text-right font-semibold">Status</th></tr></thead><tbody>{orders.slice(0, 5).map((order) => <tr key={order.id} className="border-b border-slate-50 last:border-0"><td className="py-4 text-sm font-semibold text-slate-900">#{order.marketplaceOrderId}</td><td className="py-4 text-xs text-slate-500">{channelLabel(connections.find((connection) => connection.id === order.marketplaceConnectionId)?.marketplaceType || "canal")}</td><td className="py-4 text-sm text-slate-600">{order.buyerName || "Cliente"}</td><td className="py-4 text-right text-sm font-semibold text-slate-900">{money(order.totalAmount || 0)}</td><td className="py-4 text-right"><Badge variant="outline" className="rounded-lg border-slate-200 bg-slate-50 text-xs font-medium">{order.status}</Badge></td></tr>)}</tbody></table></div> : <EmptyState icon={ShoppingCart} title="Nenhum pedido importado" description="Quando seus canais receberem pedidos, eles aparecerão aqui." action="Configurar canais" onClick={() => navigate("/marketplaces")} />}</section>
  </div>;
}

function MetricCard({ label, value, detail, icon: Icon, tone, onClick }: { label: string; value: string; detail: string; icon: typeof Boxes; tone: "blue" | "violet" | "amber" | "rose" | "emerald"; onClick: () => void }) { const styles = { blue: "bg-blue-50 text-blue-600", violet: "bg-violet-50 text-violet-600", amber: "bg-amber-50 text-amber-600", rose: "bg-rose-50 text-rose-600", emerald: "bg-emerald-50 text-emerald-600" }; return <button onClick={onClick} className="group rounded-3xl border border-slate-200/80 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-md"><div className="flex items-start justify-between"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${styles[tone]}`}><Icon className="h-4 w-4" /></div><ArrowUpRight className="h-4 w-4 text-slate-300 transition group-hover:text-slate-700" /></div><p className="mt-5 text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em] text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></button>; }
function StatusPill({ connected, error }: { connected: boolean; error?: string | null }) { return <span title={error || undefined} className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1.5 text-[11px] font-semibold ${connected && !error ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}><span className={`h-1.5 w-1.5 rounded-full ${connected && !error ? "bg-emerald-500" : "bg-rose-500"}`} />{connected && !error ? "Operacional" : "Atenção"}</span>; }
function ActionRow({ icon: Icon, tone, title, detail, onClick }: { icon: typeof AlertCircle; tone: "rose" | "amber" | "violet" | "emerald"; title: string; detail: string; onClick: () => void }) { const styles = { rose: "bg-rose-50 text-rose-600", amber: "bg-amber-50 text-amber-600", violet: "bg-violet-50 text-violet-600", emerald: "bg-emerald-50 text-emerald-600" }; return <button onClick={onClick} className="flex w-full items-center gap-3 rounded-2xl p-2 text-left transition hover:bg-slate-50"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${styles[tone]}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-800">{title}</p><p className="truncate text-xs text-slate-400">{detail}</p></div><ArrowUpRight className="h-4 w-4 text-slate-300" /></button>; }
function EmptyState({ icon: Icon, title, description, action, onClick }: { icon: typeof Globe2; title: string; description: string; action: string; onClick: () => void }) { return <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 px-5 py-10 text-center"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-slate-100 text-slate-400"><Icon className="h-5 w-5" /></div><p className="mt-3 text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-400">{description}</p><Button variant="outline" size="sm" className="mt-4 rounded-xl" onClick={onClick}>{action}</Button></div>; }
