import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Boxes, ChevronRight, Factory, Gauge, Layers3, PackageSearch, RefreshCw, ShieldCheck, Truck, WalletCards } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useLocation } from "wouter";

const money = (value: number) => `R$ ${(value / 100).toLocaleString("pt-BR", { minimumFractionDigits: 2 })}`;

export default function Supply() {
  const [, navigate] = useLocation();
  const { data: summary, isLoading, refetch } = trpc.supply.dashboard.useQuery();
  const { data: suppliers = [] } = trpc.supply.suppliers.list.useQuery();
  const { data: supplierProducts = [] } = trpc.supply.catalog.list.useQuery({});
  const { data: mappings = [] } = trpc.supply.mappings.list.useQuery({});

  return <div className="mx-auto max-w-[1500px] space-y-7">
    <section className="relative overflow-hidden rounded-[28px] bg-slate-950 px-6 py-7 text-white shadow-xl shadow-slate-950/10 md:px-9 md:py-8">
      <div className="absolute -right-20 -top-24 h-72 w-72 rounded-full bg-emerald-500/20 blur-3xl" /><div className="absolute bottom-[-100px] right-[22%] h-56 w-56 rounded-full bg-blue-500/15 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.2em] text-emerald-300"><Factory className="h-3.5 w-3.5" /> Luary Supply Engine</div><h1 className="max-w-2xl text-3xl font-semibold tracking-[-0.04em] md:text-4xl">Abasteça melhor. Venda com confiança.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Fornecedores, custo real, disponibilidade, risco e fulfillment conectados ao Produto Mestre — sem duplicar seu estoque ou publicar sem aprovação.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => navigate("/supply/suppliers")} className="rounded-xl bg-white text-slate-950 hover:bg-slate-100"><Factory className="mr-2 h-4 w-4" /> Fornecedores</Button><Button onClick={() => refetch()} variant="outline" className="rounded-xl border-white/20 bg-white/10 text-white hover:bg-white/15 hover:text-white"><RefreshCw className="mr-2 h-4 w-4" /> Atualizar visão</Button></div></div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Fornecedores" value={isLoading ? "—" : String(summary?.suppliers ?? 0)} detail="Fontes cadastradas" icon={Factory} tone="emerald" />
      <Metric label="Produtos de origem" value={isLoading ? "—" : String(summary?.products ?? 0)} detail="Catálogo externo" icon={Boxes} tone="blue" />
      <Metric label="Dropshipping" value={isLoading ? "—" : String(summary?.dropshipping ?? 0)} detail="Políticas ativas" icon={Truck} tone="violet" />
      <Metric label="Alertas críticos" value={isLoading ? "—" : String(summary?.blockedSuppliers ?? 0)} detail="Fornecedores bloqueados" icon={ShieldCheck} tone="rose" />
    </section>

    <div className="grid gap-5 xl:grid-cols-[1.2fr_0.8fr]">
      <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Rede de abastecimento</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Fornecedores monitorados</h2></div><Button variant="ghost" size="sm" onClick={() => navigate("/supply/suppliers")} className="rounded-xl text-slate-500">Gerenciar <ChevronRight className="ml-1 h-4 w-4" /></Button></div>{suppliers.length ? <div className="space-y-2">{suppliers.slice(0, 6).map((supplier) => <div key={supplier.id} className="flex items-center justify-between rounded-2xl border border-slate-100 bg-slate-50/60 p-4"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600"><Factory className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-slate-900">{supplier.name}</p><p className="text-xs text-slate-400">{supplier.integrationType} · {supplier.defaultShippingDays || "—"} dias padrão</p></div></div><Badge variant="outline" className="rounded-lg border-slate-200 bg-white text-xs">{supplier.status}</Badge></div>)}</div> : <Empty icon={Factory} title="Cadastre seu primeiro fornecedor" description="Comece pelo fornecedor que abastece seus produtos de teste." onClick={() => navigate("/supply/suppliers")} />}</section>
      <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Governança comercial</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Sem venda às cegas</h2></div><div className="space-y-3"><Signal icon={ShieldCheck} title="Supply Gate" detail="Produto, fornecedor, custo, margem, prazo e mídia precisam estar válidos." /><Signal icon={Gauge} title="Roteamento por risco" detail="Estoque, prazo, reputação e cancelamentos pesam mais que o menor custo." /><Signal icon={WalletCards} title="Landed Cost" detail="Custo real antes de sugerir preço ou avaliar margem." /></div><Button variant="outline" className="mt-5 w-full rounded-xl" onClick={() => navigate("/supply/opportunities")}>Abrir oportunidades <ChevronRight className="ml-auto h-4 w-4" /></Button></section>
    </div>

    <section className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm md:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-slate-400">Catálogo de origem</p><h2 className="mt-1 text-lg font-semibold tracking-tight text-slate-950">Produtos e vínculos</h2></div><div className="flex gap-2"><Badge className="rounded-lg bg-slate-100 text-slate-600 hover:bg-slate-100">{supplierProducts.length} produtos</Badge><Badge className="rounded-lg bg-blue-50 text-blue-700 hover:bg-blue-50">{mappings.length} mappings</Badge></div></div>{supplierProducts.length ? <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left"><thead><tr className="border-b border-slate-100 text-[11px] uppercase tracking-[0.14em] text-slate-400"><th className="pb-3 font-semibold">Produto</th><th className="pb-3 font-semibold">SKU</th><th className="pb-3 font-semibold">Custo</th><th className="pb-3 font-semibold">Estoque</th><th className="pb-3 text-right font-semibold">Status</th></tr></thead><tbody>{supplierProducts.slice(0, 10).map((product) => <tr key={product.id} className="border-b border-slate-50 last:border-0"><td className="py-4"><p className="text-sm font-semibold text-slate-900">{product.name}</p><p className="text-xs text-slate-400">{product.brand || "Marca não informada"}</p></td><td className="py-4 text-xs text-slate-500">{product.sku || "—"}</td><td className="py-4 text-sm font-semibold text-slate-800">{money(product.costCents)}</td><td className="py-4 text-sm text-slate-600">{product.stock}</td><td className="py-4 text-right"><Badge variant="outline" className="rounded-lg">{product.status}</Badge></td></tr>)}</tbody></table></div> : <Empty icon={PackageSearch} title="Catálogo de fornecedor vazio" description="Quando você importar ou cadastrar uma fonte, os produtos aparecerão aqui." onClick={() => navigate("/supply/catalog")} />}</section>
  </div>;
}

function Metric({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: typeof Factory; tone: "emerald" | "blue" | "violet" | "rose" }) { const styles = { emerald: "bg-emerald-50 text-emerald-600", blue: "bg-blue-50 text-blue-600", violet: "bg-violet-50 text-violet-600", rose: "bg-rose-50 text-rose-600" }; return <div className="rounded-3xl border border-slate-200/80 bg-white p-5 shadow-sm"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${styles[tone]}`}><Icon className="h-4 w-4" /></div><p className="mt-5 text-xs font-medium text-slate-500">{label}</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em] text-slate-950">{value}</p><p className="mt-1 text-[11px] text-slate-400">{detail}</p></div>; }
function Signal({ icon: Icon, title, detail }: { icon: typeof ShieldCheck; title: string; detail: string }) { return <div className="flex gap-3 rounded-2xl bg-slate-50 p-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-white text-emerald-600 shadow-sm"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-slate-800">{title}</p><p className="mt-0.5 text-xs leading-5 text-slate-400">{detail}</p></div></div>; }
function Empty({ icon: Icon, title, description, onClick }: { icon: typeof Factory; title: string; description: string; onClick: () => void }) { return <div className="flex flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 px-5 py-10 text-center"><Icon className="h-6 w-6 text-slate-400" /><p className="mt-3 text-sm font-semibold text-slate-800">{title}</p><p className="mt-1 max-w-xs text-xs leading-5 text-slate-400">{description}</p><Button variant="outline" size="sm" className="mt-4 rounded-xl" onClick={onClick}>Abrir módulo</Button></div>; }
